.Silent:

#NAME: Jason Less & Yun Xu
#EMAIL: jaless1997@gmail.com & x_one_u@yahoo.com
#ID: 404-640-158 & 304635157

default:
	cp lab3b.py lab3b 
	chmod +x lab3b 

clean:
	rm lab3b *.tar.gz 

dist:
	tar -zcvf lab3b-304635157.tar.gz lab3b.py Makefile README