.Silent:

#NAME: Jason Less & Yun Xu
#EMAIL: jaless1997@gmail.com & x_one_u@yahoo.com
#ID: 404-640-158 & 304635157

AUX = Makefile README lab3b.py
TARBALL_NAME = lab3b-304635157.tar.gz

default:
	@cp lab3b.py lab3b
	@chmod +x lab3b

clean:
	@rm -f lab3b *.tar.gz 

dist:
	@tar -czf $(TARBALL_NAME) $(AUX)
